import type { MetadataRoute } from 'next';

const BASE_URL = 'https://collegecomps.com';

/**
 * Dynamic robots.txt generated by the Next.js app router.
 *
 * Strategy:
 * - Allow everything by default for general crawlers (Googlebot, Bingbot, etc.)
 * - Disallow only authenticated user pages and API routes
 * - Explicitly disallow AI training bots from the whole site.
 *   (Middleware also blocks these at the request level — robots.txt just
 *   provides the public signal of intent.)
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/auth/',
          '/admin/',
          '/profile/',
          '/onboarding',
          '/subscription',
          '/edit-preferences',
          '/comparison-manager',
          '/saved-comparisons',
          '/my-timeline',
          '/alerts',
          '/exports',
          '/priority-data',
          '/submit-salary',
          '/support',
          '/dashboard',
          '/advanced-analytics',
        ],
      },
      // AI training crawlers — block from entire site.
      {
        userAgent: 'GPTBot',
        disallow: '/',
      },
      {
        userAgent: 'ChatGPT-User',
        disallow: '/',
      },
      {
        userAgent: 'OAI-SearchBot',
        disallow: '/',
      },
      {
        userAgent: 'CCBot',
        disallow: '/',
      },
      {
        userAgent: 'ClaudeBot',
        disallow: '/',
      },
      {
        userAgent: 'anthropic-ai',
        disallow: '/',
      },
      {
        userAgent: 'Claude-Web',
        disallow: '/',
      },
      {
        userAgent: 'Google-Extended',
        disallow: '/',
      },
      {
        userAgent: 'PerplexityBot',
        disallow: '/',
      },
      {
        userAgent: 'Perplexity-User',
        disallow: '/',
      },
      {
        userAgent: 'Bytespider',
        disallow: '/',
      },
      {
        userAgent: 'Amazonbot',
        disallow: '/',
      },
      {
        userAgent: 'Meta-ExternalAgent',
        disallow: '/',
      },
      {
        userAgent: 'FacebookBot',
        disallow: '/',
      },
      {
        userAgent: 'Diffbot',
        disallow: '/',
      },
      {
        userAgent: 'YouBot',
        disallow: '/',
      },
      {
        userAgent: 'cohere-ai',
        disallow: '/',
      },
      {
        userAgent: 'ImagesiftBot',
        disallow: '/',
      },
    ],
    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
